### ISSUE TITLE
Typo on website

### ISSUE THREAD

**Issue by null-dev** [sanity/kweb#18]
I had a little trouble setting up Kweb on maven until I realized there was a typo on the maven section of this page: http://kweb.io/use/getting-started.html.

**In the code block underneath:** `For Maven users, add this to the repositories section of your pom.xml`:

**On the second last line:**
`<repository><id>ktor</id><url>"http://dl.bintray.com/kotlin/ktor"</url></repository>`
should be:
`<repository><id>ktor</id><url>http://dl.bintray.com/kotlin/ktor</url></repository>` **(removed the quotes)**

**Comment by sanity** [comment]
Thank you!
